disabled_rules: # rule identifiers to exclude from running
  #Errors
  - line_length
  - trailing_comma
  - identifier_name
  - empty_parentheses_with_trailing_closure

opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - "*.playground"
